# Generated by Django 5.0.6 on 2024-07-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_categoria_alter_pedido_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('en proceso', 'En Proceso'), ('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('enviado', 'Enviado')], default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='estado',
            field=models.CharField(choices=[('en proceso', 'En Proceso'), ('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('enviado', 'Enviado')], default='Pendiente', max_length=50),
        ),
    ]
