# Generated by Django 5.0.6 on 2024-07-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_alter_pedido_estado_alter_seguimiento_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categoria'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('entregado', 'Entregado'), ('en proceso', 'En Proceso'), ('enviado', 'Enviado'), ('pendiente', 'Pendiente')], default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='estado',
            field=models.CharField(choices=[('entregado', 'Entregado'), ('en proceso', 'En Proceso'), ('enviado', 'Enviado'), ('pendiente', 'Pendiente')], default='Pendiente', max_length=50),
        ),
    ]
