# Generated by Django 5.0.6 on 2024-07-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_categoria_imagen_alter_pedido_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('en proceso', 'En Proceso'), ('entregado', 'Entregado')], default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='precio',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('en proceso', 'En Proceso'), ('entregado', 'Entregado')], default='Pendiente', max_length=50),
        ),
    ]
