# Generated by Django 5.0.6 on 2024-07-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_alter_pedido_estado_alter_pedido_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('en proceso', 'En Proceso'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('pendiente', 'Pendiente')], default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='estado',
            field=models.CharField(choices=[('en proceso', 'En Proceso'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('pendiente', 'Pendiente')], default='Pendiente', max_length=50),
        ),
    ]
