# Generated by Django 5.0.6 on 2024-07-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_alter_pedido_estado_alter_seguimiento_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('en proceso', 'En Proceso'), ('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('enviado', 'Enviado')], default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='estado',
            field=models.CharField(choices=[('en proceso', 'En Proceso'), ('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('enviado', 'Enviado')], default='Pendiente', max_length=50),
        ),
    ]
